spring:
  datasource:
    url: jdbc:mysql://106.52.234.126:3306/qzDS?useUnicode=true&useSSL=true
    username: root
    password: benben425_ximi
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

request:
  url: http://172.20.41.180:58085/nmswt/restws/bizman/sendBizData
  #未启用
  port:
  queryParam: ?dataType=FM
  #定时任务只会发送五分钟内未发送成功的数据
  overSeconds: -300
  #失败重发次数
  reSendTimes: 3

code:
    aiCode: 1000
    biCode: 2000
mybatis: 
  mapper-locations:
  - classpath:com/oneapm/alter/mapper/*.xml
  type-aliases-package: com.oneapm.alter.entity
    